name: my_package
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  # ---------
  # Пакет, который использует equatable
  # В нем нет equatable в версии 6.0.0
  # ---------
  chopper: ^6.0.0
  flutter:
    sdk: flutter
  # ---------
  # Пакет, где версия equatable: ^1.2.0 (>=1.2.0 && <2.0.0)
  # ---------
  yet_some_package:
    path: './packages/yet_some_package'

# ---------
# Пример с dependecy_overrides, тут находится форк от equatable
# ---------
#dependency_overrides:
#  equatable:
#    path: './packages/equatable'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0